name: w_common
version: 2.1.2
description: General utilities for Dart projects.
homepage: https://www.github.com/Workiva/w_common

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  js: ^0.6.5
  logging: ^1.1.1
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.6
  build_web_compilers: ^3.2.7
  dependency_validator: ^3.2.2
  mockito: ^5.3.2
  test: ^1.23.1
